id: P006792
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:23:10.141849
source_metadata:
  id: bdr:W23543
  title: གསུང་འབུམ། བློ་བཟང་རྒྱ་མཚོ།
  author: ''
  volumes:
    9c8fe2c1b64242c2aaa5a9e88711e081:
      image_group_id: I6475
      title: ''
      volume_number: 1
      total_pages: 400
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
