id: I51DDD257
legacy_id: P006792
ocr_import_info:
  bdrc_scan_id: W23543
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T23:46:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:12:29.147198+00:00'
last_modified: 2022-09-02 09:12:47.141609
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23543
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23543
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་རྒྱ་མཚོ།
  author: ཆོས་དཔལ་ཞིང་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7734329645923002
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I6475:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6475
      total_pages: 400
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6475.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7734329645923002
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
